<a href="https://colab.research.google.com/github/harika300805/ML-workshop/blob/main/mlWorkshop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1. Perform arithmetic operations on NumPy arrays.
import numpy as np
arr1=np.array([2,4,12,5,9])
arr2=np.array([3,1,8,5,7])
print("Addition of 2 arrays is: ",arr1+arr2) #or we can use add_arr=np.add(arr1,arr2)
print("Subtraction of 2 arrays is: ",arr1-arr2) #or we can use sub_arr=np.subtract(arr1,arr2)
print("Multiplication of 2 arrays is: ",arr1*arr2) #or we can use mul_arr=np.multiply(arr1,arr2)
print("Division of 2 arrays is: ",arr1/arr2) #or we can use div_arr=np.divide(arr1,arr2)
print("Remainder using numpy arrays: ",np.mod(arr1,arr2))
print("Power function using numpy arrays: ",np.power(arr1,2))


Addition of 2 arrays is:  [ 5  5 20 10 16]
Subtraction of 2 arrays is:  [-1  3  4  0  2]
Multiplication of 2 arrays is:  [ 6  4 96 25 63]
Division of 2 arrays is:  [0.66666667 4.         1.5        1.         1.28571429]
Remainder using numpy arrays:  [2 0 4 0 2]
Power function using numpy arrays:  [  4  16 144  25  81]


In [ ]:
#2. Write a script to compute the mean and standard deviation of a NumPy array.
import numpy as np
arr=np.array([12,23,34,45,56])
print("Mean of the array is: ",np.mean(arr))
print("Standard deviation of the array is: ",np.std(arr))


Mean of the array is:  34.0
Standard deviation of the array is:  15.556349186104045


In [ ]:
#3. Create a NumPy array of integers from 10 to 50 with a step size of 5.
a=np.arange(10,51,5)
print("Numpy array : ", a)

Numpy array :  [10 15 20 25 30 35 40 45 50]


In [ ]:
#4. Reshape the array into a 2x4 matrix.
a=a[:8]
Array=a.reshape(2,4)
print("Reshaped array : ",Array)

Reshaped array :  [[10 15 20 25]
 [30 35 40 45]]


In [ ]:
'''5. Given the array arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]):
      • Extract the sub-matrix containing the last two rows and first two columns.
      • Replace all elements greater than 4 with 0. '''
Arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
Arr1=Arr[1: , :2]
print("Sub-matrix of the array:\n ",Arr1)
for i in range(3):
  for j in range(3):
    if Arr[i,j] >4 :
      Arr[i,j] = 0
print("ALtered array :\n",Arr)


Sub-matrix of the array:
  [[4 5]
 [7 8]]
ALtered array :
 [[1 2 3]
 [4 0 0]
 [0 0 0]]


In [ ]:
'''6. Create two 1D arrays:
      • a = np.array([1, 2, 3])
      • b = np.array([4, 5, 6])
      • Perform element-wise addition, multiplication, and division.'''
a=np.array([1,2,3])
b=np.array([4,5,6])
add_ab=np.add(a,b)
mul_ab=np.multiply(a,b)
div_ab=np.divide(a,b)
print("Addtion: ",add_ab)
print("Multiplication: ",mul_ab)
print("Division: ",div_ab)

Addtion:  [5 7 9]
Multiplication:  [ 4 10 18]
Division:  [0.25 0.4  0.5 ]


In [ ]:
'''7. Create a random NumPy array of size (4, 4). Compute:
      • Mean of each column.
      • Maximum value of the entire array.
      • Sum of all elements.'''
r_arr=np.random.rand(4,4)
mean_r=np.mean(r_arr,axis=0)
max_r=np.max(r_arr)
sum_r=np.sum(r_arr)
print("Mean of each column: ",mean_r)
print("Maximum value of the array: ", max_r)
print("Sum of elements in array: ",sum_r)

Mean of each column:  [0.59737269 0.43339439 0.56785644 0.46343513]
Maximum value of the array:  0.9757208114357039
Sum of elements in array:  8.248234552381334


In [ ]:
'''8. Given the array arr = np.array([1, 2, 3, 4]), add 10 to each element and multiply
      the result by 2. '''
array=np.array([1,2,3,4])
array=(array+10)*2
print("Altered array: ", array)

Altered array:  [22 24 26 28]


In [ ]:
'''9. Perform advanced slicing and indexing on a 3D array.
      Create a 3D NumPy array arr of shape (3, 4, 5) with random integers ranging from
      1 to 100. Perform the following:
      • Extract the second "layer" (i.e., the second 2D array) in the first dimension.
      • Extract the first two rows and the last three columns from each "layer."
      • Replace all elements divisible by 3 with -1. '''
import numpy as np
arr=np.random.randint(1,101,(3,4,5))
print(arr)
arr1=arr[: ,1:2, ]
print("Extracted array no.1: \n",arr1)
arr2=arr[:, :2, -3: ]
print("Extracted array no.2: \n",arr2)
for i in range(3):
  for j in range(4):
    for k in range(5):
      if arr[i][j][k]%3 == 0 :
        arr[i][j][k]=-1
print("Replaced array: \n",arr)


[[[35 43 95 99 51]
  [45 35 46 34 19]
  [98 17 56 28 58]
  [12 26  6 11 52]]

 [[29 95 54 28 68]
  [26 62 43 17 95]
  [96 72 98 74 14]
  [49  4 81 53 27]]

 [[60 31 20 42 70]
  [33 10 89 80 25]
  [60 16 16 31 52]
  [ 2 26 16 97 44]]]
Extracted array no.1: 
 [[[45 35 46 34 19]]

 [[26 62 43 17 95]]

 [[33 10 89 80 25]]]
Extracted array no.2: 
 [[[95 99 51]
  [46 34 19]]

 [[54 28 68]
  [43 17 95]]

 [[20 42 70]
  [89 80 25]]]
Replaced array: 
 [[[35 43 95 -1 -1]
  [-1 35 46 34 19]
  [98 17 56 28 58]
  [-1 26 -1 11 52]]

 [[29 95 -1 28 68]
  [26 62 43 17 95]
  [-1 -1 98 74 14]
  [49  4 -1 53 -1]]

 [[-1 31 20 -1 70]
  [-1 10 89 80 25]
  [-1 16 16 31 52]
  [ 2 26 16 97 44]]]


In [37]:
'''10. Work with broadcasting and advanced operations in NumPy.
        Create a NumPy array arr of shape (3, 3) with random integers between
        1 and 20. Perform the following:
        • Subtract the mean of each row from its respective elements (row-wise
        normalization).
        • Create a new array by squaring all the elements in arr.
        • Find the indices of the top 3 maximum values in the entire array.'''
import numpy as np
a=np.random.randint(1,21,(3,3))
print(a)
a1=a.copy()
mean_a=np.mean(a,axis=1)
for i in range(3):
  a1[i]=a[i]-mean_a[i]
print("Subtracted array: \n",a1)
sq_a=np.power(a,2)
print("Squared array: \n",sq_a)
m=a1[0][0]
ind_l=[]
for i in range(3):
  for j in range(3):
    if a[i][j] > m:
      m=a[i][j]
      ind=[i,j]
    ind_l.append(ind)
    a[i][j]=0
print("Indices of top 3 maximum elements :\n ", ind_l[-3:])



[[ 6 11 16]
 [ 2  9 14]
 [ 1 17 19]]
Subtracted array: 
 [[ -5   0   5]
 [ -6   0   5]
 [-11   4   6]]
Squared array: 
 [[ 36 121 256]
 [  4  81 196]
 [  1 289 361]]
Indices of top 3 maximum elements :
  [[0, 2], [2, 1], [2, 2]]
